# Generated by Django 6.0.3 on 2026-03-28 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='subjetct',
            new_name='subject',
        ),
    ]
